name: lightweight
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py37h06a4308_0
  - faiss-cpu=1.7.1=py3.7_h2a577fa_1_cpu
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libfaiss=1.7.1=h2bc3f7f_1_cpu
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=heee7806_1
  - numpy-base=1.21.2=py37h79a1101_0
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.0.1=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - alembic==1.7.5
    - anyio==3.3.4
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - async-generator==1.10
    - async-timeout==4.0.1
    - asynctest==0.13.0
    - attrs==21.2.0
    - autopage==0.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - backports-entry-points-selectable==1.1.1
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - bs4==0.0.1
    - cffi==1.15.0
    - cfgv==3.3.1
    - charset-normalizer==2.0.7
    - chromedriver-autoinstaller==0.2.2
    - click==8.0.3
    - cliff==3.10.0
    - cmaes==0.8.2
    - cmd2==2.3.2
    - colorama==0.4.4
    - colorlog==6.6.0
    - configparser==5.1.0
    - crayons==0.4.0
    - cryptography==36.0.0
    - cython==0.29.24
    - datasets==1.16.1
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - dill==0.3.4
    - distlib==0.3.3
    - docker-pycreds==0.4.0
    - elasticsearch==7.16.1
    - emoji==1.6.1
    - entrypoints==0.3
    - faiss==1.5.3
    - fastapi==0.70.0
    - filelock==3.4.0
    - flask==2.0.2
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.24
    - greenlet==1.1.2
    - h11==0.12.0
    - huggingface-hub==0.1.2
    - identify==2.4.0
    - idna==3.3
    - importlib-metadata==4.8.1
    - importlib-resources==5.4.0
    - ipykernel==6.5.0
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - itsdangerous==2.0.1
    - jedi==0.18.0
    - jinja2==3.0.2
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.2.1
    - jupyter-client==6.1.12
    - jupyter-core==4.9.1
    - jupyter-server==1.11.2
    - jupyterlab==3.2.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - kss==3.3.1.1
    - mako==1.1.6
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multidict==5.2.0
    - multiprocess==0.70.12.2
    - nbclassic==0.3.4
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - nodeenv==1.6.0
    - nose==1.3.7
    - notebook==6.4.5
    - numpy==1.21.4
    - optuna==2.4.0
    - outcome==1.1.0
    - packaging==21.2
    - pandas==1.1.5
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pathtools==0.1.2
    - pbr==5.8.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - platformdirs==2.4.0
    - pre-commit==2.9.3
    - prettytable==2.4.0
    - prometheus-client==0.12.0
    - promise==2.3
    - prompt-toolkit==3.0.22
    - protobuf==3.19.1
    - psutil==5.8.0
    - psycopg2-binary==2.9.2
    - ptflops==0.6.6
    - ptyprocess==0.7.0
    - pyarrow==6.0.1
    - pycparser==2.21
    - pydantic==1.8.2
    - pygments==2.10.0
    - pymysql==1.0.2
    - pyopenssl==21.0.0
    - pyparsing==2.4.7
    - pyperclip==1.8.2
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.3.0
    - regex==2021.11.10
    - requests==2.26.0
    - sacremoses==0.0.46
    - scikit-learn==0.24.1
    - scipy==1.7.3
    - selenium==4.1.0
    - send2trash==1.8.0
    - sentry-sdk==1.5.0
    - shortuuid==1.0.8
    - smmap==5.0.0
    - sniffio==1.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.1
    - split-folders==0.4.3
    - sqlalchemy==1.4.27
    - starlette==0.16.0
    - stevedore==3.5.0
    - subprocess32==3.5.4
    - tensorly==0.7.0
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - toml==0.10.2
    - torch==1.6.0
    - torchvision==0.7.0
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.1
    - transformers==4.12.5
    - trio==0.19.0
    - trio-websocket==0.9.2
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - virtualenv==20.10.0
    - voila==0.2.16
    - wandb==0.12.7
    - wcwidth==0.2.5
    - webdriver-manager==3.5.2
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - werkzeug==2.0.2
    - wsproto==1.0.0
    - xxhash==2.0.2
    - yarl==1.7.2
    - yaspin==2.1.0
    - zipp==3.6.0
prefix: /opt/conda/envs/lightweight
